const UPDATE_MAP_STYLE_DATA = 'UPDATE_MAP_STYLE_DATA';
const UPDATE_MAP_STYLE_SELECTION = 'UPDATE_MAP_STYLE_SELECTION';

export default {
    UPDATE_MAP_STYLE_DATA,
    UPDATE_MAP_STYLE_SELECTION,
};
