const UPDATE_CENTER = 'UPDATE_CENTER';
const UPDATE_ZOOM = 'UPDATE_ZOOM';
const UPDATE_MIN_ZOOM = 'UPDATE_MIN_ZOOM';
const UPDATE_MAX_ZOOM = 'UPDATE_MAX_ZOOM';

export default {
    UPDATE_CENTER,
    UPDATE_ZOOM,
    UPDATE_MIN_ZOOM,
    UPDATE_MAX_ZOOM,
};
